source 'https://github.com/CocoaPods/Specs.git'
workspace 'PubNub.xcworkspace'
xcodeproj 'PushMe/PushMe.xcodeproj'

target 'PushMe', :exclusive => true do
	platform :ios, '8.0'
	pod "PubNub", "~> 4.0"
end
